apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-db
  namespace: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-db
  template:
    metadata:
      labels:
        app: booking-db
    spec:
      initContainers:
        - name: copy-init-sql
          image: busybox
          command: ['sh', '-c', 'cp /init/init.sql /initdb/init.sql']
          volumeMounts:
            - name: init-sql
              mountPath: /initdb
            - name: init-sql-config
              mountPath: /init
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: booking-config
            - secretRef:
                name: booking-secrets
          volumeMounts:
            - name: booking-db-data
              mountPath: /var/lib/postgresql/data
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: booking-db-data
          persistentVolumeClaim:
            claimName: booking-db-pvc
        - name: init-sql
          emptyDir: {}
        - name: init-sql-config
          configMap:
            name: booking-init-sql
---
apiVersion: v1
kind: Service
metadata:
  name: booking-db
  namespace: booking-app
spec:
  selector:
    app: booking-db
  ports:
    - port: 5432
      targetPort: 5432
