apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: booking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: booking-service
          image: revilllo/booking-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@booking-db:5432/bookingdb"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: booking-app
spec:
  selector:
    app: booking-service
  ports:
    - port: 3001
      targetPort: 3001
