const Project = () => (
    <main className="home-main">
        <h1>Project requirements</h1>
        <h2>And how I wanted to kill myself</h2>
        <p>
            This project was a nightmare. I had to learn React, TypeScript, and Tailwind CSS all at once.
            The requirements were vague, and the deadline was tight. I spent countless hours debugging,
            only to find out that the problem was a missing semicolon or a typo in a variable name.
            <p>^ autogenerated Copilot text is a DIVA lmao</p>
        </p>
    </main>
);

export default Project;